services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/src
    ports:
      - 8000:8000
    volumes:
      - ./src:/home/src
    stdin_open: true
    entrypoint: /bin/bash
